import Head from 'next/head';

import { TopPage } from '../components/TopPage';
import { About } from '../components/About';
import { client } from '../lib/client';

import { Products } from '../components/Products';
import type { Product } from '../../types/product';

export type ProductsProps = {
  products: Array<Product>;
};

export default function Home({ products }: ProductsProps) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <TopPage />
      <About />
      <Products products={products} />
    </div>
  );
}

export const getStaticProps = async () => {
  const data = await client.get({ endpoint: 'products' });

  return {
    props: {
      products: data.contents,
    },
  };
};
